name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12", "3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: list env contents
      run: |
        conda info
        conda list
        pip list
    - name: Lint with flake8
      run: |
        # ignore star import (F401+F403).
        # ignore whitespace before ':' (E203)
        # ignore line too long (E501).
        # same maxlinelenght as black.
        flake8 . --count --extend-ignore=F401,F403,E203,E501 --max-line-length=88 --exclude="docs,examples" --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov=kenmerkendewaarden --cov-report xml --cov-report term
    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}